<body class="bg-black">
    <div class="container w-50 m-auto border mt-5 h-75 rounded text-danger text-center fs-1">
        <div class="row ">
            <div class="col">
                Login using spotify buddy !!!<br>
                press the button   

            </div>

        </div>
        <div class="row p-5">
            <div class="col">
            <a class="btn btn-primary rounded-pill fs-3" href="/api/spotify" role="button">Login using Spotify</a>
            </div>

        </div>
        
    </div>

</body>